SpinalHDL/SpinalDoc-RTD

source/SpinalHDL/Getting Started/Scala Guide/basics.rst, source/SpinalHDL/Getting Started/Scala Guide/coding_conventions.rst, source/SpinalHDL/Getting Started/Scala Guide/index.rst, source/SpinalHDL/Getting Started/Scala Guide/interaction.rst
Just some corrections for minor spelling mistakes and other small clarifications.
=> Scala Guide: Spelling and rewording

source/SpinalHDL/Other language features/formal.rst, source/SpinalHDL/Other language features/index.rst
=> add formal page to Other language features

source/SpinalHDL/Data types/bundle.rst, source/SpinalHDL/Design errors/assignment_overlap.rst, source/SpinalHDL/Design errors/index.rst, source/SpinalHDL/Design errors/latch_detected.rst, source/SpinalHDL/Design errors/spinal_cant_clone.rst, source/SpinalHDL/Design errors/unassigned_register.rst, source/SpinalHDL/Design errors/unreachable_is_statement.rst, source/SpinalHDL/Design errors/width_mismatch.rst
There are still a lot of typos left
=> Fixed typos

source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Data types/bits.rst
Refers to [#245](https://github.com/SpinalHDL/SpinalHDL/issues/245) of SpinalHDL
=> added documentation of literal construction out of BigInts

source/SpinalHDL/Structuring/components_hierarchy.rst
Closes https://github.com/SpinalHDL/SpinalHDL/issues/254
=> Document `setDefinitionName` and other changes

source/SpinalHDL/Getting Started/getting_started.rst
Repo will checkout into folder "SpinalTemplateSbt"
"sbt run" will open a menu, added a comment so that the docs do not seem out of date
=> Fix small errors in Getting Started

source/SpinalHDL/Libraries/stream.rst
Small cleanup of Stream documentation.
=> Add StreamJoin + cleanup of StreamFork

source/SpinalHDL/Libraries/stream.rst
- Add detailed description of expected behavior of the signals in a
Stream bundle
- Fix minor typos
=> Add detailed protocol description to Stream

source/SpinalHDL/Examples/Intermediates ones/uart.rst
Forgive my poor English please.
=> Add uart example for an unreleased feature.

source/SpinalHDL/Libraries/EDA/altera/quartus_flow.rst
miaou.addAttribute("altera_attribute", "-name VIRTUAL_PIN ON")
=> A tip about virtual pin.

source/SpinalHDL/Other language features/index.rst, source/SpinalHDL/Other language features/report.rst
Relevant issue: https://github.com/SpinalHDL/SpinalHDL/issues/398
=> Add page for report feature

README.rst, source/SpinalHDL/Data types/bits.rst, source/SpinalHDL/Data types/bool.rst, source/SpinalHDL/Data types/enum.rst, source/SpinalHDL/Design errors/spinal_cant_clone.rst, source/SpinalHDL/Other language features/scope_property.rst, source/SpinalHDL/Semantic/when_switch.rst, source/SpinalHDL/Sequential logic/memory.rst, source/SpinalHDL/Structuring/components_hierarchy.rst, source/conf.py
Here are the commits on the things I missed when learning the language (+ a few typos).
Basically if I had to look at the SpinalHDL sources, it means that something was missing in the docs.
=> Updating docs on the things I found missing while learning the language

source/SpinalHDL/Semantic/when_switch.rst
Just showing how to add several cases in the same is-clause, separating them with a comma.
=> Switch Is clause factorization

source/SpinalHDL/Sequential logic/registers.rst
Examples to create vectors of registers, with examples for simple of more complex initialization methods.
=> Register vectors

source/SpinalHDL/Data types/AFix.rst, source/SpinalHDL/Data types/index.rst
I haven't used sphinx before so feel free to correct me.
=> Add AFix documentation

source/SpinalHDL/Structuring/clock_domain.rst
sync document of discussion of https://github.com/SpinalHDL/SpinalHDL/pull/715
=> example of specify a register reset-type as boot

source/SpinalHDL/Sequential logic/registers.rst
https://github.com/SpinalHDL/SpinalHDL/issues/729
=> Add set as reg

source/SpinalHDL/Libraries/regIf.rst
Also, there are some fixes in the RegIf documentation.
Relates to SpinalHDL/SpinalHDL#900.
=> Add SystemRDL RegIf exporter documentation

source/SpinalHDL/Libraries/stream.rst
documentation for StreamMux and StreamDemux, for SpinalHDL/SpinalHDL#901 .
=> add StreamMux and StreamDemux usage

source/SpinalHDL/Data types/Fix.rst
Add documentation for methods added in https://github.com/SpinalHDL/SpinalHDL/pull/970
I'll open this as a draft as the SpinalHDL PR is not yet merged.
=> Add new overloads for XFix.truncated

source/SpinalHDL/Introduction/Projects using SpinalHDL.rst
Thanks for hosting us at the conference!
=> Add LeafLabs to list of companies

source/SpinalHDL/Introduction/Projects using SpinalHDL.rst
=> Fix the link format of Elitestek

source/SpinalHDL/Introduction/Projects using SpinalHDL.rst
Preview available: https://numero-744.github.io/SpinalDoc-RTD/master/SpinalHDL/Introduction/Projects%20using%20SpinalHDL.html
=> add companies and universities

source/SpinalHDL/Libraries/regIf.rst
doc https://github.com/SpinalHDL/SpinalHDL/pull/1035
=> [regif] add setReservedAddressReadValue API

examples/src/main/scala/spinaldoc/libraries/flow/FlowExample.scala, examples/src/main/scala/spinaldoc/libraries/flow/SimSupport.scala, source/SpinalHDL/Libraries/flow.rst
Add simulation support section like in "Stream" to "Flow" and move Flow example to examples to be compiled.
=> Flow simulation support and compile example

LICENSE, source/SpinalHDL/Data types/bits.rst, source/SpinalHDL/Libraries/utils.rst, source/SpinalHDL/miscelenea/frequent_errors.rst, source/SpinalHDL/miscelenea/index.rst, source/SpinalHDL/miscelenea/lib/briey/hardware.rst, source/SpinalHDL/miscelenea/lib/briey/hardware_toplevel.rst, source/SpinalHDL/miscelenea/lib/briey/introduction.rst, source/index.rst
* makes Miscellaneous content accessible (quite a bit of content, confirm it should be public)
* removed TravisCI SVG badge that 404s
* Fix error/warning due to missing column in table "Range"
* LICENSE file missing first character
These 2 items don't necessarily need to be in PR, but are required in my source branch so that it can be built in a github action (maybe I can rename the source branch of this PR from 'https://github.com/dlmiles/SpinalDoc-RTD/tree/dev' to 'https://github.com/dlmiles/SpinalDoc-RTD/tree/dev-pr179' to if separation is required:
* bin/convert-wrapper
* .github/workflows/build-and-depoy.yml  this is my all in one action test/live linkcheck/no-linkcheck  single/multi  deploy
EDIT this build failure https://github.com/SpinalHDL/SpinalDoc-RTD/actions/runs/4928725690/job …
=> Cleanup dev branch

source/SpinalHDL/Introduction/Projects using SpinalHDL.rst
-* `DatenLord, China <https://datenlord.github.io/en/home.html>`_ 
+* `DatenLord, China <https://datenlord.github.io/>`_
Look like they updated their website in the past few days ?
=> linkfix: Introduction/Projects using SpinalHDL: https://datenlord.github.io

source/SpinalHDL/Data types/Int.rst
A fix of #181 and switch to master branch.
=> describe how wrap method work for UInt type.

requirements.txt, source/conf.py
Closes https://github.com/SpinalHDL/SpinalDoc-RTD/issues/146
=> Sphinx: add extensions shinx-copybutton

source/SpinalHDL/Legacy/pinsec/hardware.rst
Browsable preview at: https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/index.html
https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/SpinalHDL/Legacy/pinsec/hardware.html
See review marker looking for assistance to reword this area.  Thanks
=> Legacy/pinsec/hardware: updated (REVIEW/REWORD requested)

source/SpinalHDL/Data types/bits.rst, source/SpinalHDL/Data types/bool.rst
Sorry these typos escaped even with the lastest draft.
=> Tranche 2 typo fixes

source/SpinalHDL/Data types/Int.rst
Browsable preview at: https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/index.html
https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/SpinalHDL/Data%20types/Int.html
See review marker looking for assistance to reword this area. Thanks
=> Data types/Int: updated

source/SpinalHDL/Libraries/Bus/avalon/avalonmm.rst
=> Issue197: Update Avalon Interface Specifications PDF URL

source/SpinalHDL/Data types/bundle.rst, source/SpinalHDL/Structuring/blackbox.rst, source/SpinalHDL/Structuring/parametrization.rst
Browsable preview at: https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/index.html
https://dlmiles.github.io/SpinalDoc-RTD/docs_multi/html/vTEST/SpinalHDL/Data%20types/bundle.html
See review marker looking for assistance to reword this area. Thanks
=> Data types/bundle: updated (generate keyword)

source/SpinalHDL/Getting Started/Install and setup.rst
Added Mac OS X installation instructions.  Since I do not have a second mac to test the installation instructions, it may not be perfect, but better than nothing.
=> Update Install and setup.rst

source/SpinalHDL/Getting Started/SBT.rst, source/SpinalHDL/Structuring/clock_domain.rst, source/conf.py
Fix #211 and add some notes for stuff recently needed on Gitter
=> Fix mixup and clarify ClockDomain details

source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Data types/bits.rst, source/SpinalHDL/Data types/bool.rst
Use unusual n-times to not have to write 'repeat x n times'
=> Add documentation for #* operator

source/SpinalHDL/Structuring/clock_domain.rst
Adds a warning about clock usage in SlowArea (see SpinalHDL/SpinalHDL#1287)
=> clock_domain: warn about clock wire in SlowArea

source/SpinalHDL/Libraries/regIf.rst, source/locale/gettext/SpinalHDL/Libraries/regIf.pot, source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Libraries/regIf.po
for this pr in SpinalHDL: https://github.com/SpinalHDL/SpinalHDL/pull/1300
=> add description for SpinalEnum resetValue in RegIf field

source/SpinalHDL/Libraries/utils.rst
For: https://github.com/SpinalHDL/SpinalHDL/pull/1359
=> Add CountLeadingZeroes to documentation

source/SpinalHDL/Data types/bits.rst
x(x: UInt) to x(y: UInt) according to Description "Variable bit access of y-th bit"
=> Update bits.rst in Bit extraction

source/SpinalHDL/Data types/Int.rst
x(x: UInt) to x(y: UInt) according to Description "Variable bit access of y-th bit"
=> Update Int.rst about Bit extraction

source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Libraries/Pipeline/introduction.po, source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Libraries/fsm.po, source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Other language features/assertion.po
=> update chinese version to latest.

.github/workflows/push-doc.yml, source/_templates/versions.html, source/conf.py
=> add pdf and related version generating for Chinese.
