source/SpinalHDL/Simulation/install.rst
Verilator seems to have changed to semantic versioning.
Fixes the tag to make install instructions valid again.
=> Fix verilator tag name in install instructions

source/SpinalHDL/Libraries/IO/tristate.rst, source/SpinalHDL/Other language features/analog_inout.rst
As discussed a few days ago on gitter, the TriState documentation is a bit out-of-date.
I therefore would propose to:
- Remove notes from TriState that state that Analog is not yet implemented
- Cross-reference TriState and Analog pages
- Add notes about how to drive Analog manually
- Fix minor typos
=> Update TriState and Analog descriptions

source/SpinalHDL/About SpinalHDL/faq.rst, source/SpinalHDL/About SpinalHDL/support.rst, source/SpinalHDL/About SpinalHDL/users.rst
This PR consists of small formatting, spelling, and grammatical fixes for the "About SpinalHDL" section of the docs.
=> Fix grammar/formatting in About SpinalHDL section

source/SpinalHDL/Data types/Fix.rst, source/SpinalHDL/Data types/Floating.rst, source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Data types/Vec.rst, source/SpinalHDL/Data types/bits.rst, source/SpinalHDL/Data types/bool.rst, source/SpinalHDL/Data types/bundle.rst, source/SpinalHDL/Data types/enum.rst, source/SpinalHDL/Data types/index.rst, source/SpinalHDL/Examples/index.rst
This PR includes:
- Basic spelling/grammatical/formatting fixes and improvements.
- More descriptive hyperlink text where possible. ("here" -> "article
on <topic>")
- New link target to the Examples page, to make cross-linking easier.
- Code examples are formatted more consistently now.
- More code-style wrappers to highlight SpinalHDL types in the text.
=> Copyediting fixes for Datatypes section.

source/SpinalHDL/Structuring/area.rst, source/SpinalHDL/Structuring/blackbox.rst, source/SpinalHDL/Structuring/clock_domain.rst, source/SpinalHDL/Structuring/components_hierarchy.rst, source/SpinalHDL/Structuring/function.rst
This PR includes spelling/grammar/formatting fixes, as well as the
following:
- `addPrePostTask` on the blackboxing page is now updated to be
`addPrePopTask`, along with some explanatory text.
=> Copyediting fixes for Structuring section.

source/SpinalHDL/Data types/Fix.rst
This PR adds some clarification about how the `exp` function works for the `SFix`/`UFix` types. It can seem rather "magical" when first encountered, so the hope here is to disambiguate why it exists, and make its usage and effects more obvious to readers.
=> Document the `exp` constructor's usage on the SFix/UFix page.

source/SpinalHDL/Sequential logic/memory.rst, source/SpinalHDL/Sequential logic/registers.rst
This commit includes spelling/grammar/formatting edits for the pages in
the Sequential logic section, as well as:
- Additional intra-project links.
- New ref-target in the memory page for cross-linking the automatic
blackboxing features mentioned throughout the page.
=> Copyedits for the Sequential logic section.

source/SpinalHDL/Design errors/assignment_overlap.rst, source/SpinalHDL/Design errors/clock_crossing_violation.rst, source/SpinalHDL/Design errors/combinatorial_loop.rst, source/SpinalHDL/Design errors/hierarchy_violation.rst, source/SpinalHDL/Design errors/index.rst, source/SpinalHDL/Design errors/iobundle.rst, source/SpinalHDL/Design errors/latch_detected.rst, source/SpinalHDL/Design errors/no_driver_on.rst, source/SpinalHDL/Design errors/nullpointerexception.rst, source/SpinalHDL/Design errors/register_defined_as_component_input.rst, source/SpinalHDL/Design errors/scope_violation.rst, source/SpinalHDL/Design errors/spinal_cant_clone.rst, source/SpinalHDL/Design errors/unassigned_register.rst, source/SpinalHDL/Design errors/unreachable_is_statement.rst, source/SpinalHDL/Design errors/width_mismatch.rst
This PR includes spelling/grammar/formatting fixes for the Design
Errors section, as well as the following additional changes:
- Verilator project link on the "combinatorial loop" page where the
simulator is mentioned.
=> Copyedits for the Design Errors section.

source/SpinalHDL/Other language features/analog_inout.rst, source/SpinalHDL/Other language features/assertion.rst, source/SpinalHDL/Other language features/formal.rst, source/SpinalHDL/Other language features/index.rst, source/SpinalHDL/Other language features/utils.rst, source/SpinalHDL/Other language features/vhdl_generation.rst
This commit includes spelling/grammar/formatting fixes for the
Other language features section, as well as the following changes:
- Added link to the Github issue tracker where it was referenced.
- Multi-sentence lines are broken up into multiple lines now, one
line per sentence, to help with future diff-tracking.
=> Copyedits for the Other language features section.

source/SpinalHDL/Structuring/clock_domain.rst
This adds a note about register capture that was not obvious to me even after reading this chapter (https://github.com/SpinalHDL/SpinalHDL/issues/614).
=> clock_domains.rst: add note about register capture

source/SpinalHDL/Structuring/clock_domain.rst
Explain the prioirties of reset and clock enable signals in the clock domain class, and a small example is given.
=>  add 'Signal priorities in HDL generation'

source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Design errors/clock_crossing_violation.rst, source/SpinalHDL/Developers area/bus_slave_factory_impl.rst, source/SpinalHDL/Developers area/types.rst, source/SpinalHDL/Examples/Advanced ones/jtag.rst, source/SpinalHDL/Examples/Intermediates ones/uart.rst, source/SpinalHDL/Examples/Intermediates ones/vga.rst, source/SpinalHDL/Examples/Simple ones/apb3.rst, source/SpinalHDL/Getting Started/Help for VHDL people/vhdl_comp.rst, source/SpinalHDL/Getting Started/Scala Guide/coding_conventions.rst, source/SpinalHDL/Libraries/Bus/amba3/apb3.rst, source/SpinalHDL/Libraries/Graphics/vga.rst, source/SpinalHDL/Libraries/stream.rst, source/SpinalHDL/Other language features/analog_inout.rst, source/SpinalHDL/Other language features/stub.rst, source/SpinalHDL/Other language features/vhdl_generation.rst, source/SpinalHDL/Semantic/assignments.rst, source/SpinalHDL/Sequential logic/registers.rst, source/SpinalHDL/Structuring/area.rst, source/SpinalHDL/Structuring/blackbox.rst, source/SpinalHDL/Structuring/clock_domain.rst, source/SpinalHDL/Structuring/components_hierarchy.rst, source/SpinalHDL/miscelenea/core/core_components.rst, source/SpinalHDL/miscelenea/regular_hdl.rst
A lot of non data type pages still used bit instead of bits like:
UInt(8 bit). Replaced them with s/bit)/bits)/g in all files.
Signed-off-by: Daniel Schultz <dnltz@aesc-silicon.de>
=> Replace "x bit" with "x bits"

source/SpinalHDL/Libraries/binarySystem.rst, source/SpinalHDL/Libraries/regIf.rst
documentation for https://github.com/SpinalHDL/SpinalHDL/pull/693
1.  fied(HardType(T))
2. add RALF(UVM Register Abstraction Layer Generator) supported 
3. setName add on RegInst and Field
4. mv lib.bus.regif.Document._ to lib.bus.regif._
please merge  after next SpinalHDL version( >= 1.6.5)  release
=> regif API update 

source/SpinalHDL/Libraries/binarySystem.rst, source/SpinalHDL/Libraries/regIf.rst, source/SpinalHDL/Simulation/examples/dual_clock_fifo.rst
Fix some minor problems in Libraries and Simulation 
val a = 32.toBigInt        a is 32
There is an error with the same code on the official website
change to Apb3BusInterface
Interrupt Factory There are  small problems
1. is setWhen  no setwhen
2.is  frame_int_raw no fram_int_force
3. Status No driver 
Because clk_B in StreamFifoCC does not reset, but the default clock will reset, you need to manually add withReset=false  
And the dut. PopClock. DeassertReset () and dut popClock. AssertReset () have to delete
=> Fix some minor problems in Libraries and Simulation

source/SpinalHDL/Libraries/stream.rst
I know that there is currently no documentation of simulation utilities with their respective SpinalHDL constructs so this is kind of a first - still makes sense to me though, for me this is the most likely location to search for it (apart from RTFS)
=> Add Stream simulation driver/monitor docs

source/SpinalHDL/Design errors/latch_detected.rst, source/SpinalHDL/Semantic/when_switch.rst
Contrary to what was described it is in a fully covered mux not allowed to not have a default, it is prohibited.
Also do a bit of a shuffle to not understate muxListDc before having introduced muxList
=> Fix behavior of 'default' in when

source/SpinalHDL/Semantic/assignments.rst
It would be suuuuper cool to automatically test examples of docs, [like what is done with Rustdoc](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#passing-or-failing-a-doctest) (should I open an issue with suggestions to do this?).
=> fix: assignment overlap in Semantic/assignments

source/SpinalHDL/Libraries/stream.rst
It was not building. Now it builds but it still does not pass the test.
The test fails: `Timeout trigger after 10000 units of time`
=> fix: last example "Simulation support"

.github/workflows/push-doc.yml, .github/workflows/test-build.yml, Dockerfile, README.rst, pdf.Dockerfile, requirements.txt, source/_templates/versions.html, source/conf.py
Fix #132 
I still have to add it to GitHub actions, but there is still discussion needed in #132 about this.
=> ci: pdf generation with docker

source/SpinalHDL/Data types/enum.rst, source/SpinalHDL/Libraries/fsm.rst
Add encoding added in https://github.com/SpinalHDL/SpinalHDL/pull/967
Also fixes broken syntax highlighting on the FSM page.
For now I did not extract the code examples to our checked build, I'd leave that for a separate commit that does not add any now code to make the review easier.
=> Add graySequential enum encoding

source/SpinalHDL/Semantic/when_switch.rst
For #138 discussed in [SpinalHDL/SpinalHDL#946](https://github.com/SpinalHDL/SpinalHDL/issues/946) 
also added documentation for the strict option since its part of the same structure and would belong in the same place.
I am open for slightly less technical/deep descriptions of these parameters as I dont know if it would confuse anyone reading that first time.
=> document coverUnreachable and strict options for the switch block

source/SpinalHDL/Developers area/mill support.rst
Content is as title described.
However, this failed in my CI by error "source/SpinalHDL/Data types/bits.rst:265: ERROR: Error parsing content block for the "list-table" directive: uniform two-level bullet list expected, but row 3 does not contain the same number of items as row 1 (2 vs 3)."
@numero-744 can you have a look at it?
=> document building SpinalHDL with mill

source/SpinalHDL/Introduction/faq.rst
Closes #157 
Available on <https://numero-744.github.io/SpinalDoc-RTD/master/SpinalHDL/Introduction/faq.html#how-to-use-an-unreleased-version-of-spinalhdl-but-committed-on-git>
=> Choosing scalaVersion with publishLocal

source/SpinalHDL/Introduction/Projects using SpinalHDL.rst
Elitestek has used the VexRISC-V core in FPGAs and applied in multi applications in worldwide customers.
=> Add Elitestek to companies using SpinalHDL page

source/SpinalHDL/Simulation/install/Verilator.rst
in [tool.sh](https://github.com/SpinalHDL/SpinalHDL/blob/4a21ab4cca95b35fbb12189077e7609e7b40dbb9/tools.sh#L9), the version of verilator is updated to `v4.218`, while the Doc still recommands the `v4.040`, maybe we need to update the Doc
=> update verilator's version from v4.040 -> v4.218

source/SpinalHDL/Data types/Int.rst
It strikes me as weird that no one noticed this but
```scala
case class TestX() extends Component {
val i = in Bits(128 bit)
val o = out Bits(32 bit)
o := i.subdivideIn(32 bit)(0)
}
object TestXX extends App {
SpinalVerilog(TestX())
}
```
generates
```
module TestX (
input      [127:0]  i,
output     [31:0]   o
);
assign o = i[31 : 0];
endmodule
```
Which indicates that the ordering was documented incorrectly
=> Fix order of slices from subdivideIn

examples/build.sbt
Simply update so that we can use e.g. `in port Bool()`
=> Update SpinalHDL version for examples to 1.8.0b

.github/workflows/build-and-deploy.yml, .github/workflows/push-doc.yml, .github/workflows/test-build.yml, .gitignore, Dockerfile, bin/convert-wrapper, bin/setup_env.sh, pdf.Dockerfile, requirements.txt, source/_static/dialog.js, source/_static/gh-fork-ribbon.css, source/_static/gh-fork-ribbon.txt, source/_static/github-corner-right.css, source/_static/github-corner-right.svg, source/_static/github-corner-right.txt, source/_static/spinaldoc.css, source/_templates/footer.html, source/_templates/layout.html, source/_templates/page.html, source/_templates/versions.html, source/conf.py
*  meta: canonical added
*  meta: robots added (for test builds, google ignore)
*  building 'latest' label as alias to v1.8.0
*  bottom: Version info line
*  github-action builder updates (param stuff, build multiversion)
*  github-action deploy works on local fork
*  top right 'fork me on github'
*  left side version warning box (dismisses for 24h, URL param override)
*  CSS attempt for narrow/mobile compat
* CI building using a single script for all modes
Needs testing in production.
Then setup of 'on schedule' to autobuild and publish every month, to counter 3 monthly gh-pages retention policy.
Note the default setup will run the linkcheck which may fail at the time of the 'on schedule' maybe skipping linkcheck for the 'on schedule' is more appropriate to recreate the last version …
=> Global project updates

source/SpinalHDL/Other language features/utils.rst
Document second variant of `Cat` and elaborate on the differences.
=> Expand on Cat

source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Data types/bits.rst
This started out just wanting to move subdivide to the access functions, but now ended in a few additional changes. Among the bigger ones that e.g. `abs` and similar functions are now listed as "conversion" functions, some additional examples and a fix to the output order of `subdivideIn` in the examples.
=> Clarify subdivide

source/SpinalHDL/Data types/Fix.rst
Updated a fix for the table rappresenting the Logic operation with Fixed point. the table shows x>y twice.
=> Update Fix.rst comparison table

source/SpinalHDL/Getting Started/VSCodium.rst
More detailed comments in the first and third commit messages. 
Next time I will sync the repositories before editing.
=> Changes to: Using Spinal from VSCodium

examples/src/main/scala/spinaldoc/sequential_logic/memory_sim.scala, source/SpinalHDL/Sequential logic/memory.rst, source/SpinalHDL/Simulation/signal.rst, source/SpinalHDL/miscelenea/core/core_components.rst
Shifted down the memory access documentation since the example uses `simPublic`.
Remove some legacy documentation and adapt headline to make memory docs easier to find (if user searches for "Memory")
=> Document mem sim api

source/SpinalHDL/Libraries/Bus/tilelink/tilelink.rst, source/SpinalHDL/Libraries/Bus/tilelink/tilelink_fabric.rst
=> Add tilelink doc

source/SpinalHDL/Semantic/assignments.rst
Documenting CombInit, since I stumble upon it and I did not see any description in the docs.
=> Add a documentation for CombInit

source/SpinalHDL/Examples/Intermediates ones/vga.rst
The link from xess.com have dead, which prevent the link checking.
=> fix the link that vga explaination is dead.

source/SpinalHDL/Getting Started/Install and setup.rst
update scala sbt download url to latest.
=> fix the url for scala sbt download.

source/SpinalHDL/Libraries/flow.rst, source/locale/gettext/SpinalHDL/Libraries/flow.pot, source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Libraries/flow.po
Caught on problem caused by #248. ^^
=> fix the error caused by wrong format of newly added stage function description.

source/SpinalHDL/Getting Started/Install and setup.rst, source/SpinalHDL/Libraries/utils.rst, source/SpinalHDL/Structuring/blackbox.rst
Based on my limited understanding of [The UART workshop solution](https://github.com/SpinalHDL/SpinalWorkshop/blob/9fd30eb3071b6849ce676fb3086cc2fc22ff731e/src/main/scala/workshop/uart/assets/UartCtrlRx.solution#L34) and [spinalhdl lib code](https://github.com/SpinalHDL/SpinalHDL/blob/768f0960f581c3160c4ef14ebb03928f1f9e2db5/lib/src/main/scala/spinal/lib/Utils.scala#L1218), I updated the documentation. 
Please check that the description is valid, I'm very new to all of that.
=> Add doc for `History(that, range)`

README.rst, source/SpinalHDL/Examples/Simple ones/sinus_rom.rst, source/SpinalHDL/Libraries/bus_slave_factory.rst, source/SpinalHDL/Semantic/when_switch.rst
Based on implementations present in directory /lib/src/main/scala/spinal/lib/bus of spinalHDL v1.10.2 .
=> Correct supported slave factory

source/SpinalHDL/Developers area/howotuselocalspinalclone.rst
Lately I have been bitten by countless ``SCOPE VIOLATION`` or ``HIERARCHY VIOLATION`` errors that I did not know where they came from. It drove me crazy.
Thanks to https://github.com/SpinalHDL/SpinalHDL/issues/1387 I noticed that I _simply_ set up my sbt build wrong. I was using Spinal from a local git clone (actually my fork of it) and didnt notice the missing scalac options. (I kinda dislike sbt, I think it is very complicated and slow...)
Nonetheless, I wanted to spare others from pain and try to document it a bit.
~~Todo: the mill side of it is missing as I don't use mill. Does someone have a working configuration for it?~~
=> describe how to use local spinal clone as dependency

source/SpinalHDL/Simulation/clock.rst, source/locale/gettext/SpinalHDL/Simulation/clock.pot, source/locale/zh_CN/LC_MESSAGES/SpinalHDL/Simulation/clock.po
This is in correspondence to the pull request opened in SpinalHDL main repo
=> Adding small addition for waitInactiveEdge and waitInactiveEdgeWhere

.github/workflows/build-and-deploy.yml, source/SpinalHDL/Data types/bool.rst, source/SpinalHDL/Developers area/howotuselocalspinalclone.rst, source/SpinalHDL/Developers area/types.rst, source/SpinalHDL/Formal verification/index.rst, source/SpinalHDL/Getting Started/Help for VHDL people/vhdl_comp.rst, source/SpinalHDL/Getting Started/Install and setup.rst, source/SpinalHDL/Introduction/A simple example.rst, source/SpinalHDL/Legacy/pinsec/hardware_toplevel.rst, source/SpinalHDL/Libraries/Pipeline/introduction.rst, source/SpinalHDL/Libraries/stream.rst, source/SpinalHDL/Libraries/utils.rst, source/SpinalHDL/Other language features/vhdl_generation.rst, source/SpinalHDL/Semantic/assignments.rst, source/SpinalHDL/Semantic/when_switch.rst, source/SpinalHDL/Sequential logic/registers.rst, source/SpinalHDL/Structuring/blackbox.rst, source/SpinalHDL/Structuring/components_hierarchy.rst, source/SpinalHDL/miscelenea/core/core_components.rst
The only change in meaning is here:
```
StageCtrlPipeline
-----------------
Very similar to ``StagePipeline``, but it replace Nodes by ``CtrlLink``, allowing to handle
the arbitration / bypasses on each stages, which is for instance quite useful for CPU designs.
```
StageLink is replaced by CtrlLink.
=> Typo, presentation and `wire` -> `signal` improvment

examples/src/main/scala/spinaldoc/examples/advanced/Slots.scala, source/SpinalHDL/Data types/Int.rst, source/SpinalHDL/Examples/Advanced ones/slots.rst, source/SpinalHDL/Introduction/Projects using SpinalHDL.rst, source/SpinalHDL/Libraries/Bus/tilelink/tilelink_fabric.rst, source/SpinalHDL/Libraries/Pipeline/introduction.rst, source/SpinalHDL/Libraries/fiber.rst, source/SpinalHDL/Libraries/stream.rst, source/SpinalHDL/Sequential logic/memory.rst, source/SpinalHDL/Structuring/clock_domain.rst
I added VexiiRiscv reference in Fiber because it's interesting as a code example.
I did not add it to the misc.pipeline doc, because it's probably too complicate as a pipeline example (Vexii redefine a it own class in top of le lib).
=> Add extra blackbox description and fix typo and presentation
